---
language: python
cache: pip
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
    - python: nightly
  allow_failures:
    - python: 3.8-dev
    - python: nightly

install:
  - pip install --upgrade pip setuptools black
  - pip install .

script:
  - python setup.py test && find . -type f -name '*.py' | xargs black --check
