---
language: python
cache: pip
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: nightly

install:
  - pip install --upgrade pip setuptools coverage black
  - pip install -e .

script:
  - coverage run tests/test_bugbear.py
  - coverage report -m | grep 'bugbear\.py'
  - black --check .
