---
language: python
cache: pip
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
      env: PYTHON_VER=py38
  allow_failures:
    - env: PYTHON_VER=py38

install:
  - pip install black
  - pip install -e .

script:
  - python setup.py test && find . -type f -name '*.py' | xargs black --check
