name: pypi_upload

on:
  release:
    types: [created]

jobs:
  upload:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install latest pip, build & twine
      run: |
        python -m pip install --upgrade pip build twine

    - name: Build sdist + wheel
      run: |
        python -m build

    - name: Upload to PyPI via Twine
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine check dist/*
        twine upload --verbose -u '__token__' dist/*
