name: rst_check

on: [push, pull_request]

jobs:
  check_syntax:
    name: RST Syntax Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Update pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install rstcheck
      run: |
        python -m pip install rstcheck

    - name: Run rstcheck
      run: |
        rstcheck README.rst
